[[main]]
  name = "About"
  pageRef = "/docs/about/credits/"
  weight = 10
  [main.params]
    alias = true

[[main]]
  name = "Docs"
  pageRef = "/docs/"
  weight = 20

[[main]]
  name = "Content Blocks"
  pageRef = "/docs/content-blocks"
  weight = 30

[[main]]
  name = "Components"
  pageRef = "/docs/components/"
  weight = 40
  [main.params]
    alias = true

[[main]]
  name = "Guides"
  pageRef = "/guides/"
  weight = 50

[[main]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/gethinode/hinode"
  weight = 60
  [main.params]
    icon = true
      
# toml-docs-start sample-navigation
[[sample]]
  name = "About"
  pageRef = "/docs/about/credits/"
  weight = 10
  [sample.params]
    alias = true

[[sample]]
  name = "Guides"
  pageRef = "/guides/"
  weight = 30

[[sample]]
  parent = "Guides"
  name = "Getting started"
  pageRef = "/guides/editing/"
  weight = 10

[[sample]]
  parent = "Guides"
  name = "Developing Hugo modules"
  pageRef = "/guides/modules/"
  weight = 20

[[sample]]
  parent = "Guides"
  name = "Optimization"
  pageRef = "/guides/optimization/"
  weight = 30

[[sample]]
  name = "GitHub"
  url = "https://github.com/gethinode/hinode"
  weight = 40
# toml-docs-end sample-navigation

[[alias]]
  name = "About"
  pageRef = "/docs/about/credits/"
  weight = 10
  [alias.params]
    alias = true

[[alias]]
  name = "About (no alias)"
  pageRef = "/docs/about/credits/"
  weight = 20

[[alias]]
  name = "Guides"
  pageRef = "/guides/"
  weight = 30

[[alias]]
  parent = "Guides"
  name = "Getting started"
  pageRef = "/guides/editing/"
  weight = 10

[[alias]]
  parent = "Guides"
  name = "Developing Hugo modules"
  pageRef = "/guides/modules/"
  weight = 20

[[alias]]
  parent = "Guides"
  name = "Optimization"
  pageRef = "/guides/optimization/"
  weight = 30

[[alias]]
  name = "GitHub"
  url = "https://github.com/gethinode/hinode"
  weight = 40

[[footer]]
  name = "Links"
  weight = 10

[[footer]]
  parent = "Links"
  name = "Home"
  pageRef = "/"
  weight = 1

[[footer]]
  parent = "Links"
  name = "About"
  pageRef = "/docs/about/credits/"
  weight = 10
  [footer.params]
    alias = true

[[footer]]
  parent = "Links"
  name = "Docs"
  pageRef = "/docs/"
  weight = 20

[[footer]]
  parent = "Links"
  name = "Content blocks"
  pageRef = "/docs/content-blocks/"
  weight = 30

[[footer]]
  parent = "Links"
  name = "Components"
  pageRef = "/docs/components/"
  weight = 40
  [footer.params]
    alias = true

[[footer]]
  name = "Guides"
  weight = 20

[[footer]]
  parent = "Guides"
  name = "Getting started"
  pageRef = "/guides/editing"
  weight = 10

[[footer]]
  parent = "Guides"
  name = "Developing modules"
  pageRef = "/guides/modules"
  weight = 20

[[footer]]
  parent = "Guides"
  name = "Optimization"
  pageRef = "/guides/optimization"
  weight = 30

[[footer]]
  parent = "Guides"
  name = "Versioning"
  pageRef = "/guides/versioning"
  weight = 40

[[footer]]
  name = "Community"
  weight = 30

[[footer]]
  parent = "Community"
  name = "Issues"
  url = "https://github.com/gethinode/hinode/issues"
  weight = 10

[[footer]]
  parent = "Community"
  name = "Discussions"
  url = "https://github.com/gethinode/hinode/discussions"
  weight = 20

[[footer]]
  parent = "Community"
  name = "Contribute"
  pageRef = "/docs/getting-started/contribute/"
  weight = 30
